-- =====================================================
-- OBSOLETO. La función claim_name ahora se define (de forma NO destructiva,
-- conservando el perfil y migrando referencias) en:
--   migration-account-persistence.sql
-- Este archivo se dejó vacío a propósito para que re-correr la carpeta
-- no reintroduzca la versión vieja que borraba el perfil.
-- =====================================================
