-- =====================================================
-- OBSOLETO. Las funciones claim_name, claim_with_password y
-- _migrate_user_refs ahora se definen (versión completa, que además migra
-- follows/seguidores y vistas de perfil) en:
--   migration-account-persistence.sql
-- Este archivo se dejó vacío a propósito para que re-correr la carpeta
-- no reintroduzca una versión vieja incompleta.
-- =====================================================
